# This is a basic workflow to help you get started with Actions

name: Workflow for Codecov

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Pre requisite installation
      - name: Prerequisite installation
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install poetry
        run: pip3 install poetry

      # Runs the preparation
      - name: Prepare working environment
        run: poetry install --all-extras

      # Runs the test
      - name: Run unittests
        run: poetry run coverage run -m pytest

      # Run the coverage
      - name: Run coverage
        run: poetry run coverage xml

      # Upload the test result
      - name: Upload test-result to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
